apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: miosys-com-br-certificate
spec:
  secretName: miosys-ssl
  issuerRef:
    name: letsencrypt-staging
    kind: Issuer
    group: cert-manager.io
  commonName: miosys.com.br
  dnsNames:
  - miosys.com.br