apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: miosys-com-br-tls
  namespace: default
spec:
  secretName: miosys-com-br-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: miosys.com.br
  dnsNames:
  - miosys.com.br
  - www.miosys.com.br
  - api.miosys.com.br
