apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-staging-certificate
spec:
  secretName: miosys-ssl
  issuerRef:
    name: letsencrypt-staging
    kind: Issuer
  commonName: miosys.com.br
  dnsNames:
  - miosys.com.br
  - www.miosys.com.br