kind: Gateway
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: miosys-gateway
  annotations:
    networking.gke.io/certmap: miosys-com-br-map
spec:
  gatewayClassName: gke-l7-regional-external-managed
  listeners:
  - name: https
    protocol: HTTPS
    port: 443
