apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: miosys-route
spec:
  parentRefs:
    - kind: Gateway
      name: miosys-gateway
  hostnames:
  - "miosys.com.br"
  rules:
  - matches:
    - path:
        value: /
        type: Exact
    backendRefs:
    - name: nginx-service
      port: 8080
