kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: miosys-route
spec:
  parentRefs:
  - kind: Gateway
    name: miosys-gateway
  rules:
  - matches:
    - path:
        value: /de
    backendRefs:
    - name: miosys-rest-api-stock-counter-service
      port: 8080
