kind: Gateway
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: miosys-prod-web
spec:
  gatewayClassName: gke-l7-regional-external-managed
  listeners:
  - name: http
    protocol: http
    port: 80
  addresses:
  - type: NamedAddress
    value: miosys-external-ip
  allowedRoutes:
    kinds:
    - kind: HTTPRoute
    namespaces:
      from: Same
