apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: miosys-prod-web
spec:
  gatewayClassName: gke-l7-rilb
  listeners:
  - protocol: HTTP
    port: 80
    name: miosys-prod-web-gw
    allowedRoutes:
      namespaces:
        from: Same
