apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: miosys-gateway
  annotations:
    cert-manager.io/issuer: letsencrypt
spec:
  gatewayClassName: gke-l7-regional-external-managed
  addresses:
    - type: NamedAddress
      value: miosys-api-ip
  listeners:
  - name: http
    hostname: "*.miosys.com.br"
    port: 80 
    protocol: HTTP
    allowedRoutes:
      namespaces:
         from: All
  - name: https
    hostname: miosys.com.br  # Required
    protocol: HTTPS
    port: 443
    tls:
      mode: Terminate # Required. "Terminate" is the only supported mode.
      certificateRefs:
      - name: web-ssl # Required
        kind: Secret # Required. "Secret" is the only valid value.
        group: ""
    allowedRoutes:
      namespaces:
        from: All
