apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: miosys-gateway
spec:
  gatewayClassName: gke-l7-regional-external-managed
  listeners:
  - name: miosys-gateway-web
    protocol: HTTP
    port: 80
  addresses:
    - type: NamedAddress
      value: miosys-api-ip
